### ISSUE TITLE
Piscem crash - am I running out of memory?

### ISSUE THREAD

**Issue by jaspitzer** [COMBINE-lab/piscem#22] opened 2024-06-07 09:04 UTC
Hi everyone, 

I'm running the simpleaf wrapper and at some point into the analysis, piscem crashes, giving me the following error code (full input & output below):
`command unsuccessful (signal: 6 (SIGABRT) (core dumped))`
After some preliminary googling, it seems to be related to memory issues, so am I just running out of memory? 

```

simpleaf quant \
--reads1 $reads1 \
--reads2 $reads2 \
--threads 16 \
--index data/human-2020-A_splici/index \
--chemistry 10xv2 --resolution cr-like \
--expected-ori fw --unfiltered-pl \
--t2g-map data/human-2020-A_splici/index/t2g_3col.tsv \
--output quants
2024-06-06T09:58:28.178615Z  INFO simpleaf::simpleaf_commands::quant: piscem map-sc cmd : /home/js/mambaforge/envs/af/bin/piscem map-sc --index data/human-2020-A_splici/index/piscem_idx --threads 16 -o quants/af_map --max-ec-card 4096 --skipping-strategy permissive --max-hit-occ 256 --max-hit-occ-recover 1024 --max-read-occ 2500 -1 fastqs/SRR10134385_1.fastq.gz,fastqs/SRR10134386_1.fastq.gz,fastqs/SRR10134387_1.fastq.gz,fastqs/SRR10134388_1.fastq.gz,fastqs/SRR10134390_1.fastq.gz,fastqs/SRR25112327_1.fastq.gz,fastqs/SRR25112328_1.fastq.gz,fastqs/SRR25112329_1.fastq.gz,fastqs/SRR25112330_1_fastqc.html,fastqs/SRR25112330_1_fastqc.zip,fastqs/SRR25112330_1.fastq.gz,fastqs/SRR25112331_1.fastq.gz,fastqs/SRR25112332_1.fastq.gz -2 fastqs/SRR10134385_2.fastq.gz,fastqs/SRR10134386_2.fastq.gz,fastqs/SRR10134387_2.fastq.gz,fastqs/SRR10134388_2.fastq.gz,fastqs/SRR10134390_2.fastq.gz,fastqs/SRR25112327_2.fastq.gz,fastqs/SRR25112328_2.fastq.gz,fastqs/SRR25112329_2.fastq.gz,fastqs/SRR25112330_2_fastqc.html,fastqs/SRR25112330_2_fastqc.zip,fastqs/SRR25112330_2.fastq.gz,fastqs/SRR25112331_2.fastq.gz,fastqs/SRR25112332_2.fastq.gz --geometry chromium_v2
2024-06-06T16:11:43.447195Z ERROR simpleaf::utils::prog_utils: command unsuccessful (signal: 6 (SIGABRT) (core dumped)): "/home/js/mambaforge/envs/af/bin/piscem" "map-sc" "--index" "data/human-2020-A_splici/index/piscem_idx" "--threads" "16" "-o" "quants/af_map" "--max-ec-card" "4096" "--skipping-strategy" "permissive" "--max-hit-occ" "256" "--max-hit-occ-recover" "1024" "--max-read-occ" "2500" "-1" "fastqs/SRR10134385_1.fastq.gz,fastqs/SRR10134386_1.fastq.gz,fastqs/SRR10134387_1.fastq.gz,fastqs/SRR10134388_1.fastq.gz,fastqs/SRR10134390_1.fastq.gz,fastqs/SRR25112327_1.fastq.gz,fastqs/SRR25112328_1.fastq.gz,fastqs/SRR25112329_1.fastq.gz,fastqs/SRR25112330_1_fastqc.html,fastqs/SRR25112330_1_fastqc.zip,fastqs/SRR25112330_1.fastq.gz,fastqs/SRR25112331_1.fastq.gz,fastqs/SRR25112332_1.fastq.gz" "-2" "fastqs/SRR10134385_2.fastq.gz,fastqs/SRR10134386_2.fastq.gz,fastqs/SRR10134387_2.fastq.gz,fastqs/SRR10134388_2.fastq.gz,fastqs/SRR10134390_2.fastq.gz,fastqs/SRR25112327_2.fastq.gz,fastqs/SRR25112328_2.fastq.gz,fastqs/SRR25112329_2.fastq.gz,fastqs/SRR25112330_2_fastqc.html,fastqs/SRR25112330_2_fastqc.zip,fastqs/SRR25112330_2.fastq.gz,fastqs/SRR25112331_2.fastq.gz,fastqs/SRR25112332_2.fastq.gz" "--geometry" "chromium_v2"
2024-06-06T16:11:43.448025Z ERROR simpleaf::utils::prog_utils: stderr :
====
2024-06-06T09:58:28.219167Z  INFO piscem: cmd: ["sc_ref_mapper", "-i", "data/human-2020-A_splici/index/piscem_idx", "-g", "chromium_v2", "-1", "fastqs/SRR10134385_1.fastq.gz,fastqs/SRR10134386_1.fastq.gz,fastqs/SRR10134387_1.fastq.gz,fastqs/SRR10134388_1.fastq.gz,fastqs/SRR10134390_1.fastq.gz,fastqs/SRR25112327_1.fastq.gz,fastqs/SRR25112328_1.fastq.gz,fastqs/SRR25112329_1.fastq.gz,fastqs/SRR25112330_1_fastqc.html,fastqs/SRR25112330_1_fastqc.zip,fastqs/SRR25112330_1.fastq.gz,fastqs/SRR25112331_1.fastq.gz,fastqs/SRR25112332_1.fastq.gz", "-2", "fastqs/SRR10134385_2.fastq.gz,fastqs/SRR10134386_2.fastq.gz,fastqs/SRR10134387_2.fastq.gz,fastqs/SRR10134388_2.fastq.gz,fastqs/SRR10134390_2.fastq.gz,fastqs/SRR25112327_2.fastq.gz,fastqs/SRR25112328_2.fastq.gz,fastqs/SRR25112329_2.fastq.gz,fastqs/SRR25112330_2_fastqc.html,fastqs/SRR25112330_2_fastqc.zip,fastqs/SRR25112330_2.fastq.gz,fastqs/SRR25112331_2.fastq.gz,fastqs/SRR25112332_2.fastq.gz", "-t", "16", "-o", "quants/af_map", "--max-ec-card", "4096", "--skipping-strategy", "permissive", "--max-hit-occ", "256", "--max-hit-occ-recover", "1024", "--max-read-occ", "2500"]
[2024-06-06 11:58:28.221] [info] enable structural constraints : false
[2024-06-06 11:58:28.221] [info] No poison k-mer map exists, or it was requested not to be used
[2024-06-06 11:58:28.221] [info] loading index from data/human-2020-A_splici/index/piscem_idx
[2024-06-06 11:58:33.682] [info] done loading index
processed (6976500000) reads; (6251404818) had mappings.fatal runtime error: Rust cannot catch foreign exceptions
====
Error: piscem mapping failed with exit status ExitStatus(unix_wait_status(134))
```

**Comment by rob-p** [comment] 2024-06-07 10:57
It

**Comment by jaspitzer** [comment] 2024-06-07 11:23
Hi, 

thanks for the quick reply.

I did generate an output in the specified directory, namely af_map/map.rad.
There are about 3 TB of disc space available, which is ~3x the size of all input fastqs.

I tried running with a subset of the reads (three input samples), it ran successfully with no issues. There is no info shared between the samples during the process, right? So I can just batch the samples and process like this, if we can't find the source of the error.


Installation was through conda and setting the path as per [this](https://combine-lab.github.io/alevin-fry-tutorials/2023/simpleaf-piscem/) tutorial.

Cheers
Jasper

**Comment by jaspitzer** [comment] 2024-06-07 12:48
Just just double checking: in case barcodes are used in >1 sample, those would be attributed to the same cell when preprocessing the samples together? 

The  data is publicly available through this [paper](https://www.ahajournals.org/doi/full/10.1161/ATVBAHA.120.314789) and this [project](https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA562645). 

Alternatively, here's the sra file:
[SraRunTable.txt](https://github.com/user-attachments/files/15739262/SraRunTable.txt)

Thanks for the help!

**Comment by rob-p** [comment] 2024-06-07 12:59
@jaspitzer,

  > Just just double checking: in case barcodes are used in >1 sample, those would be attributed to the same cell when preprocessing the samples together?
  
That's correct.  Given that the technical read (R1) contains only the cell barcode and UMI, there is no way for the program to know that these correspond to distinct input samples.  Therefore, all of the reads sharing the same corrected barcode will be attributed to the same cell in the output matrix, regardless of which input file they come from.  This is because a single **sample** may often consist of multiple input **files**, and so the file of origin can't safely be used as a proxy for the sample.  Thus, the "sample <-> file" mapping logically resides one level of abstraction up and one should run distinct samples separately.


  In order to make this easier to automate for experiments with many distinct samples, one could use a `simpleaf` workflow, and we are considering adding basic sample-sheet functionality where one could provide a mapping between the files and sample name and simpleaf would internally run separately for each sample.  Of course, this is just a basic loop in a script, and so support for this hasn't been the most pressing thing to date (though it would be a nice ergonomic feature to have).

--Rob

**Comment by rob-p** [comment] 2024-06-08 01:05
Hi @jaspitzer,

  Just an update here.  I wasn't able yet to reproduce this issue. I downloaded all 12 samples of this experiment and quantified them jointly, and simpleaf finished successfully (log below):

```
✦ ❯ simpleaf quant --reads1 $reads1 --reads2 $reads2 --threads 16 --index human-2020-A_splici/index --chemistry 10xv2 --resolution cr-like --expected-ori fw --unfiltere
d-pl --t2g-map human-2020-A_splici/index/t2g_3col.tsv  --output quants
2024-06-07T15:56:53.863754Z  INFO simpleaf::simpleaf_commands::quant: piscem map-sc cmd : /ssd2/rob/piscem/target/release/piscem map-sc --index human-2020-A_splici/index/piscem_idx --threads 16 -
o quants/af_map --max-ec-card 4096 --skipping-strategy permissive --max-hit-occ 256 --max-hit-occ-recover 1024 --max-read-occ 2500 -1 fastqs/SRR10134385_1.fastq.gz,fastqs/SRR10134386_1.fastq.gz,f
astqs/SRR10134387_1.fastq.gz,fastqs/SRR10134388_1.fastq.gz,fastqs/SRR10134389_1.fastq.gz,fastqs/SRR10134390_1.fastq.gz,fastqs/SRR25112327_1.fastq.gz,fastqs/SRR25112328_1.fastq.gz,fastqs/SRR251123
29_1.fastq.gz,fastqs/SRR25112330_1.fastq.gz,fastqs/SRR25112331_1.fastq.gz,fastqs/SRR25112332_1.fastq.gz -2 fastqs/SRR10134385_2.fastq.gz,fastqs/SRR10134386_2.fastq.gz,fastqs/SRR10134387_2.fastq.g
z,fastqs/SRR10134388_2.fastq.gz,fastqs/SRR10134389_2.fastq.gz,fastqs/SRR10134390_2.fastq.gz,fastqs/SRR25112327_2.fastq.gz,fastqs/SRR25112328_2.fastq.gz,fastqs/SRR25112329_2.fastq.gz,fastqs/SRR251
12330_2.fastq.gz,fastqs/SRR25112331_2.fastq.gz,fastqs/SRR25112332_2.fastq.gz --geometry chromium_v2
2024-06-07T20:47:43.154522Z  INFO simpleaf::utils::prog_utils: command returned successfully (exit status: 0)
2024-06-07T20:47:43.160926Z  INFO simpleaf::simpleaf_commands::quant: alevin-fry generate-permit-list cmd : /ssd2/rob/miniforge3/bin/alevin-fry generate-permit-list -i quants/af_map -d fw --unfil
tered-pl /ssd2/rob/.afhome/plist/10x_v2_permit.txt --min-reads 10 -o quants/af_quant
2024-06-07T21:00:47.407172Z  INFO simpleaf::utils::prog_utils: command returned successfully (exit status: 0)
2024-06-07T21:00:47.407240Z  INFO simpleaf::simpleaf_commands::quant: alevin-fry collate cmd : /ssd2/rob/miniforge3/bin/alevin-fry collate -i quants/af_quant -r quants/af_map -t 16
2024-06-07T21:04:33.886042Z  INFO simpleaf::utils::prog_utils: command returned successfully (exit status: 0)
2024-06-07T21:04:33.886122Z  INFO simpleaf::simpleaf_commands::quant: cmd : "/ssd2/rob/miniforge3/bin/alevin-fry" "quant" "-i" "quants/af_quant" "-o" "quants/af_quant" "-t" "16" "-m" "human-2020-
A_splici/index/t2g_3col.tsv" "-r" "cr-like"
2024-06-07T21:05:43.437514Z  INFO simpleaf::utils::prog_utils: command returned successfully (exit status: 0)
```

In terms of the mapping data, I see there were `7433296773` total reads out of which `6650350169` (~89.5%) mapped.  This number is larger than what appeared in your log, suggesting that your run got very far but didn't quite finish mapping before returning.

One thought; did you perform your run on a shared server or anything with a job submission system? Is there any chance it timed out?  The mapping output totaled ~173G and the total other quant files ~54G; so as you suggest, it seems very unlikely disk space was a problem in your case.

**Comment by jaspitzer** [comment] 2024-06-10 08:56
Hi Rob, 

so thanks for all your help, I have found the issue: I ran fastqc on 2 of the files within the same folder and with its default naming scheme is was picked up by the find call, including the "SRR25112330_1_fastqc.html" in the reads, which (unsurprisingly) could then not be aligned. 
Sorry for wasting your time like that and thank you for the support. 

Cheers
Jasper

**Comment by rob-p** [comment] 2024-06-10 09:53
No worries! Thanks so much for circling back around, which helps me to be able to close this in a timely manner. Also, I’m glad I was able to clarify the behavior of aggregate vs. per sample mapping.

Best,
Rob

**Closed by rob-p** 2024-06-10 09:53 UTC
